-- ============================================
-- SUPABASE SETUP SQL FOR PORTFOLIO CONTACT FORM
-- ============================================
-- Run this in your Supabase SQL Editor to set up the database

-- Step 1: Create the contact_messages table
CREATE TABLE IF NOT EXISTS public.contact_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    subject TEXT NOT NULL,
    message TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Step 2: Enable Row Level Security (RLS) on the table
ALTER TABLE public.contact_messages ENABLE ROW LEVEL SECURITY;

-- Step 3: Create a policy that allows anonymous users to insert messages
CREATE POLICY "Allow public inserts" 
ON public.contact_messages 
FOR INSERT 
TO anon, authenticated 
WITH CHECK (true);

-- Step 4: Grant usage on the schema (if not already granted)
GRANT USAGE ON SCHEMA public TO anon, authenticated;

-- Step 5: Grant insert permission on the table
GRANT INSERT ON public.contact_messages TO anon, authenticated;

-- ============================================
-- HOW TO RUN THIS SQL:
-- ============================================
-- 1. Go to https://app.supabase.com
-- 2. Select your project: oxhxruwxbpwzzxbqvwlr
-- 3. Click "SQL Editor" in the left sidebar
-- 4. Click "New Query"
-- 5. Copy and paste all the SQL code above
-- 6. Click "Run" or press Ctrl + Enter
-- ============================================